---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
  annotations:
    metallb.universe.tf/address-pool: aiuken
spec:
  type: LoadBalancer
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app: minecraft-server